In [13]:
# Importación de Archivo CSV (Comma-Separated Values)
# 1. Cargar los datos de ventas desde el archivo CSV y mostrar una vista previa de las primeras filas.
import pandas as pd
datos_csv = pd.read_csv(r"C:\Users\orlan\OneDrive\Documents\Tecnicatura\2A1C - Aprendizaje Automatico\Semana 2\ventas.csv", encoding= "ISO-8859-1")
print("#1 Archivo CSV")
datos_csv.head()

#1 Archivo CSV

   id_venta       fecha  producto  cantidad  precio_unitario
0         1  2026-01-10  Notebook         2             1200
1         2  2026-01-12     Mouse         5               25
2         3  2026-01-15   Teclado         3               45
3         4  2026-01-18   Monitor         1              300

In [20]:
# Importación de Archivo JSON (JavaScript Object Notation)
# 2. Cargar los datos de clientes desde el archivo JSON y mostrar la cantidad total de clientes.
import pandas as pd
datos_json = pd.read_json(r"C:\Users\orlan\OneDrive\Documents\Tecnicatura\2A1C - Aprendizaje Automatico\Semana 2\clientes.json")
print("#2 Archivo JSON")
print("Cantidad total de clientes")
cantidad_total_clientes = len(datos_json)
print("La cantidad total de clientes es: ", cantidad_total_clientes)
datos_json.head()

#2 Archivo JSON
Cantidad total de clientes
La cantidad total de clientes es:  3

   id_cliente        nombre             email   telefono
0           1    Juan Pérez    juan@email.com  123456789
1           2   María López   maria@email.com  987654321
2           3  Carlos Gómez  carlos@email.com  456123789

In [26]:
# Importación de Archivo Excel
# 3. Cargar los datos de inventario desde la hoja de cálculo Excel y calcular el promedio de stock disponible para todos los productos.
import pandas as pd
datos_excel = pd.read_excel(r"C:\Users\orlan\OneDrive\Documents\Tecnicatura\2A1C - Aprendizaje Automatico\Semana 2\inventario.xlsx")
print("#3 Archivo Excel")
print("Promedio de stock disponible para todos los productos")
promedio = datos_excel['stock'].mean()
print("Promedio de stock disponible para todos los productos es de: ", promedio )
datos_excel.head()

#3 Archivo Excel
Promedio de stock disponible para todos los productos
Promedio de stock disponible para todos los productos es de:  26.25

   id_producto    nombre    categoria  stock  precio
0            1  Notebook  Electrónica     10    1200
1            2     Mouse   Accesorios     50      25
2            3   Teclado   Accesorios     30      45
3            4   Monitor  Electrónica     15     300